export const pageObject = [
        {
          pageLabel: "HAPPY",
          subMsg: "A little reminder:",
          msg1: "The perfect moment is right now. You got this!",
          question1: "What makes you feel happy or joyful?",
          question2: "What have you done to make you feel happy?",
          pageLabel2: "How Can I Stay Happy?",
          subMsg3: "Do what you love",
          subMsg4: "Create a goal",
          subMsg5: "Work on a goal you created",
          subMsg6: "Do something you wanted to do for a long time",
          subMsg7: "Do something kind for someone",
          imageUrl: "/image9.png",
          pageUrl: "https://kidshealth.org/en/teens/happy-life.html"
        },
        {
          pageLabel: "EXCITED",
          subMsg: "An affirmation for you.",
          msg1: "I am building myself a better life each day.",
          question1: "What is influencing your excitement?",
          question2: "Are you excited for someone or something?",
          pageLabel2: "How Can I Use my Excited?",
          subMsg3: "Make goals for yourself",
          subMsg4: "Do something out of your comfort zone",
          subMsg5: "Think about the present- what are you excited for right now?",
          subMsg6: "Take a walk to a new place",
          subMsg7: "Talk to a loved one",
          imageUrl: "/image9.png",
          pageUrl: "https://hackspirit.com/live-a-more-interesting-exciting-life/"
        },
        {
          pageLabel: "GRATEFUL",
          subMsg: "An affirmation for you.",
          msg1: "I am grateful for things that bring me joy.",
          question1: "What are you grateful for right now?",
          question2: "What are you grateful for in your life?",
          pageLabel2: "How Can I Stay Grateful?",
          subMsg3: "Find little things to appreciate",
          subMsg4: "Be observant of your surroundings",
          subMsg5: "Write down what your thanful for",
          subMsg6: "Donate to your local community",
          subMsg7: "Express how grateful you are to a loved one",
          imageUrl: "/image6.png",
          pageUrl: "https://kidshealth.org/en/teens/gratitude-practice.html",
          meditateLink: "https://missionshanti.org/meditation/",
        },
        {
          pageLabel: "HOPEFUL",
          subMsg: "An affirmation for you.",
          msg1: "You have what it takes to achieve anything you set your mind to.",
          question1: "Are you taking action to make your hopes come true?",
          question2: "If so, what are you doing to make your hopes come true?",
          pageLabel2: "How Can I Stay Hopeful?",
          subMsg3: "Plan a way to achieve your goals",
          subMsg4: "Write about what you are looking forward to",
          subMsg5: "Tell someone what you are looking forward to",
          subMsg6: "Think positvely",
          subMsg7: "Persevere",
          imageUrl: "/image7.png",
          pageUrl: "https://www.samaritans.org/how-we-can-help/if-youre-having-difficult-time/staying-hopeful/"
        },
        {
          pageLabel: "SCARED",
          subMsg: "A little reminder:",
          msg1: "You are in control of your life and emotions.",
          question1: "What are you scared or worried about?",
          question2: "Are the factors of your fear in your control?",
          pageLabel2: "How Can I Not Be Scared?",
          subMsg4: "Eat a healthy snack",
          subMsg5: "Practice yoga",
          subMsg6: "Inhale for 4 counts",
          subMsg7: "Exhale for 4 counts",
          imageUrl: "/image2.png",
          pageUrl: "https://kidshealth.org/en/teens/phobias.html#:~:text=People%20can%20overcome%20unnecessary%20fears,sensations%20like%20takeoff%20or%20turbulence",
          meditateLink: "https://missionshanti.org/meditation/",
        },
        {
          pageLabel: "SAD",
          subMsg: "An affirmation for you.",
          msg1: "I trust that I am on the right path.",
          question1: "What or who is driving your sadness?",
          question2: "Did you tell someone how you feel? ",
          pageLabel2: "How To Not Be Sad?",
          subMsg3: "Do something kind for someone else",
          subMsg4: "Learn a new hobby",
          subMsg5: "Learn something new",
          subMsg6: "Meet a new person",
          subMsg7: "Talk to a trusted person",
          imageUrl: "/image4.png",
          pageUrl: "https://actionforhappiness.org/10-keys?utm_source=google&utm_campaign=AFH-5-10keys&https://actionforhappiness.org/join-us-confirmation/*&gad_source=1"
        },
        {
          pageLabel: "FRUSTRATED",
          subMsg: "",
          msg1: "It’s okay to feel frustrated.Other people feel frustrated too.",
          question1: "What are you feeling frustrated about?",
          question2: "Why are you frustrated about it?",
          pageLabel2: "How do I Not be Frustrated?",
          subMsg4: "Inhale for 4 counts, hold for 4 counts, exhale for 4 counts",
          subMsg5: "Talk to a trusted person",
          subMsg6: "Watch a movie",
          subMsg7: "Read a book",
          imageUrl: "/image0.png",
          pageUrl: "https://kidshealth.org/en/teens/happy-life.html",
          meditateLink: "https://missionshanti.org/meditation/",
        },
        {
          pageLabel: "OVERWHELMED",
          subMsg: "",
          msg1: "You are confident and capable. Don’t sweat it. You got this.",
          question1: "Why do you feel the way you do?",
          question2: "Are you sure you feel the way you think you do?",
          pageLabel2: "How Do I Not be overwhelmed?",
          subMsg3: "Do what you love",
          subMsg5: "Listen to music",
          subMsg7: "Doodle",
          imageUrl: "/image1.png",
          pageUrl: "https://kidshealth.org/en/teens/happy-life.html",
          meditateLink: "https://missionshanti.org/meditation/",
          musicLink:" https://missionshanti.org/music/",
          journalLink: "https://missionshanti.org/journal/"
        },
        {
          pageLabel: "CALM",
          subMsg: "",
          msg1: "Calm is a sense of peacefulness. The perfect time to get things done.",
          question1: "What caused you to feel calm?",
          question2: "How do you become calm in tough situations?",
          pageLabel2: "How Can I Stay Calm?",
          subMsg3: "Complete a task on your to-do list",
          subMsg4: "Do what you love",
          subMsg5: "Treat yourself with a movie, game, or book",
          subMsg6: "Listen to soothing music",
          subMsg7: "Take rest",
          imageUrl: "/image6.png",
          pageUrl: "https://www.psychologicalhealthcare.com.au/blog/keep-calm-pressure/"
        },
        {
          pageLabel: "LONELY",
          subMsg: "",
          msg1: "You are loved. Your loneliness will pass.",
          question1: "Why are you feeling lonely right now?",
          question2: "How often do you feel left out or lonely?",
          pageLabel2: "How Can I Feel Better?",
          subMsg3: "Listen to music",
          subMsg4: "Journal about your feelings",
          subMsg5: "Volunteer or do something kind for someone",
          subMsg6: "Treat yourself to a movie or a book",
          imageUrl: "/image3.png",
          pageUrl: "https://kidshealth.org/en/teens/happy-life.html",
          musicLink:" https://missionshanti.org/music/",
          journalLink: "https://missionshanti.org/journal/"
        },
        {
          pageLabel: "I DONT KNOW",
          subMsg: "",
          msg1: "Its ok to not know how you feel",
          question1: "Do you have mixed feelings right now?",
          question2: "How often do you feel this way?",
          pageLabel2: "How to express your feelings",
          subMsg3: "Journal",
          subMsg4: "Talk to a loved one",
          subMsg5: "Go on a walk",
          subMsg6: "Do something you wanted to do for a long time",
          subMsg7: "Join a club",
          imageUrl: "/image10.png",
          pageUrl: "https://kidshealth.org/en/teens/emotional-awareness.html"
        }
      ];