import {LoginContextProvider } from '@/context/loginContext';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body><LoginContextProvider>{children}</LoginContextProvider></body>
    </html>
  )
}
